export const TITHI_MEANINGS: Record<string, string> = {
  "Pratipada": "The first lunar day. It signifies new beginnings, pioneering energy, and a solitary yet strong-willed essence.",
  "Dwitiya": "The second lunar day. It represents duality, partnership, and a nurturing, receptive nature.",
  "Tritiya": "The third lunar day. Associated with courage, power, and the drive to overcome obstacles.",
  "Chaturthi": "The fourth lunar day. Connected to Ganesh, signifying the removal of hurdles and a grounded but resilient character.",
  "Panchami": "The fifth lunar day. Represents intellect, learning, and a curious, knowledge-seeking soul.",
  "Shashthi": "The sixth lunar day. Associated with Skanda (Kartikeya), signifying youthful energy, martial spirit, and protection.",
  "Saptami": "The seventh lunar day. Dedicated to the Sun (Surya), reflecting leadership, vitality, and a radiant presence.",
  "Ashtami": "The eighth lunar day. A powerful day of transformation, deep healing, and confronting inner truths.",
  "Navami": "The ninth lunar day. Represents fierce determination, victory over challenges, and strong devotion.",
  "Dashami": "The tenth lunar day. Signifies ultimate triumph, righteousness, and a highly ethical essence.",
  "Ekadashi": "The eleventh lunar day. Highly spiritual, it fosters a focused mind, inner purification, and ascetic qualities.",
  "Dwadashi": "The twelfth lunar day. Associated with Vishnu, reflecting preservation, harmony, and a deeply compassionate nature.",
  "Trayodashi": "The thirteenth lunar day. A day of emotional depth, dissolving attachments, and seeking ultimate liberation (Moksha).",
  "Chaturdashi": "The fourteenth lunar day. Representing raw power, intense spiritual awakening, and courage in the dark.",
  "Purnima": "The full moon. Reflects completeness, abundance, emotional fullness, and a highly luminous nature.",
  "Amavasya": "The new moon. Signifies deep introspection, ancestral connection, and powerful hidden potential."
} as const;

export const NAKSHATRA_TRAITS: Record<string, string> = {
  "Ashwini": "Swift, athletic, and fiercely independent, you are a natural trailblazer with healing energy.",
  "Bharani": "Intense, creative, and transformative, you have the drive to endure and rebirth yourself through challenges.",
  "Krittika": "Sharp, brilliant, and protective, you are like a purifying fire that burns away illusions.",
  "Rohini": "Charming, fertile, and deeply creative, you possess an immense capacity for growth and aesthetic beauty.",
  "Mrigashirsha": "Curious, searching, and adaptable, you are a gentle soul always seeking deeper meaning.",
  "Ardra": "Intense, intellectual, and deeply transformative, your power lies in emotional storms that bring profound clarity.",
  "Punarvasu": "Nurturing, philosophical, and optimistic, you have the gift of bouncing back and restoring harmony.",
  "Pushya": "Caring, spiritual, and highly nourishing, you are often seen as a reliable and wise pillar for others.",
  "Ashlesha": "Mystical, penetrating, and fiercely protective, your instinctual wisdom allows you to see hidden truths.",
  "Magha": "Regal, traditional, and deeply connected to your roots, you carry a sense of ancestral pride and leadership.",
  "Purva Phalguni": "Relaxed, affectionate, and creatively expressive, you thrive in an environment of joy and connection.",
  "Uttara Phalguni": "Dependable, generous, and socially responsible, you are a builder of lasting relationships and structures.",
  "Hasta": "Skillful, adaptable, and detail-oriented, you hold the power to manifest your desires through your own hard work.",
  "Chitra": "Dynamic, creative, and brilliantly expressive, you are an architect of beauty and innovation.",
  "Swati": "Independent, diplomatic, and highly adaptable, you scatter your gifts far and wide like the gentle wind.",
  "Vishakha": "Determined, goal-oriented, and ambitious, you have an unyielding focus to achieve victory.",
  "Anuradha": "Loyal, devoted, and highly sensitive to others, you excel at building deep, meaningful connections.",
  "Jyeshtha": "Authoritative, deeply intuitive, and protective, you instinctively take charge and look after those smaller than you.",
  "Mula": "Profound, investigative, and philosophical, you are drawn to exploring the deepest roots of existence.",
  "Purva Ashadha": "Invincible, proud, and deeply emotional, you pour your energy into your passions like a boundless ocean.",
  "Uttara Ashadha": "Enduring, responsible, and highly disciplined, you are a deeply pragmatic and respected leader.",
  "Shravana": "A great listener, knowledgeable, and receptive, you absorb wisdom and understand the unspoken words.",
  "Dhanishta": "Wealthy, musical, and highly capable, you march to the beat of your own drum with immense confidence.",
  "Shatabhisha": "Mystical, deeply intellectual, and an independent thinker, you possess profound healing abilities and a secretive nature.",
  "Purva Bhadrapada": "Passionate, idealistic, and at times extreme, you are willing to sacrifice for higher causes.",
  "Uttara Bhadrapada": "Deeply compassionate, spiritually mature, and patient, your wisdom is like a calm, expansive ocean.",
  "Revati": "Empathetic, fully evolved, and deeply spiritual, you possess an unconditional love and serve as a safe harbor for others."
} as const;
